name: dotnet-8-nuget-pack

on:
  workflow_call:
    inputs:
      version_prefix:
        description: VersionPrefix MSBuild property
        required: false
        type: string
      version_suffix:
        description: Version suffix
        required: false
        type: string
      no_default_excludes:
        description: NoDefaultExcludes for dotnet pack
        required: false
        type: boolean
        default: false

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Pack
        shell: bash
        env:
          VERSION_PREFIX: ${{ inputs.version_prefix }}
          VERSION_SUFFIX: ${{ inputs.version_suffix }}
          NO_DEFAULT_EXCLUDES: ${{ inputs.no_default_excludes }}
          CI_PROJECT_URL: ${{ github.server_url }}/${{ github.repository }}
        run: |
          set -euo pipefail
          NO_DEFAULT=${NO_DEFAULT_EXCLUDES:-false}
          VERSION_PREFIX_PARAM=""; [[ -n "${VERSION_PREFIX:-}" ]] && VERSION_PREFIX_PARAM="-p:VersionPrefix=${VERSION_PREFIX}"
          VERSION_SUFFIX_PARAM=""; [[ -n "${VERSION_SUFFIX:-}" ]] && VERSION_SUFFIX_PARAM="--version-suffix=${VERSION_SUFFIX}"
          mkdir -p .cinuget
          dotnet restore
          dotnet pack --configuration Release --no-build --output .cinuget --verbosity normal $VERSION_PREFIX_PARAM $VERSION_SUFFIX_PARAM -p:NoDefaultExcludes=${NO_DEFAULT} -p:RepositoryUrl="$CI_PROJECT_URL" -p:PackageProjectUrl="$CI_PROJECT_URL"
      - name: Upload nupkg
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: .cinuget/*.nupkg
          retention-days: 1
