name: "Semantic Release"
description: "Composite action to run Release Please with our standard settings"
inputs:
  token:
    description: "GitHub token for authentication"
    required: true
  release-type:
    description: "Release type (node, simple, etc.)"
    required: false
    default: simple
  target-branch:
    description: "Branch to run release against"
    required: false
    default: main

runs:
  using: "composite"
  steps:
    - name: Run Release Please
      id: release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') || github.event_name == 'pull_request'
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ inputs.token }}
        release-type: ${{ inputs.release-type }}
        target-branch: ${{ inputs.target-branch }}

    - name: tag major and minor versions
      if: ${{ steps.release.outputs.release_created }}
      shell: bash
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/googleapis/release-please-action.git"
        git tag -d v${{ steps.release.outputs.major }} || true
        git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
        git push origin :v${{ steps.release.outputs.major }} || true
        git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
        git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
        git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
        git push origin v${{ steps.release.outputs.major }}
        git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
