name: "Semantic Release"
description: "Composite action to run Release Please with our standard settings"
inputs:
  token:
    description: "GitHub token for authentication"
    required: true
  release-type:
    description: "Release type (node, simple, etc.)"
    required: false
    default: simple
  target-branch:
    description: "Branch to run release against"
    required: false
    default: main

runs:
  using: "composite"
  steps:
    - name: Run Release Please
      id: release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') || github.event_name == 'pull_request'
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ inputs.token }}
        release-type: ${{ inputs.release-type }}
        target-branch: ${{ inputs.target-branch }}
        skip-github-pull-request: true
